### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by amihaiemil** [opencharles/charles#91]
Currently the travis build is failing (probably because the changes on amihaiemil.com). Let's fix it.

**Comment by amihaiemil** [comment]
@SherifWaly Would you like to also have a look here? No need to fix it, just try and find the problem. Here is the description of the project: http://www.amihaiemil.com/2016/12/05/project-charles.html

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to see it and I'll try to find the problem.

**Comment by amihaiemil** [comment]
@SherifWaly I saw you wanted to merge a PR to your fork. They should be made and merged to the main repo :D

**Comment by SherifWaly** [comment]
@amihaiemil I was just trying to see if it would run the tests as ``System.getProperty("phantomjsExec")`` is returning ``null`` and I think I have a problem with the installed phantomjs. Sorry for disturbance :)

**Comment by amihaiemil** [comment]
@SherifWaly no disturbance, no worries :) you should set that system property, unless the phantomjs exec is in the right place (see readme).

**Comment by amihaiemil** [comment]
@SherifWaly i meant the readme from charles-rest, there it is explained

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will see where is the problem. Thanks :)

**Comment by amihaiemil** [comment]
@SherifWaly but I think it would be easier if you use a graphical browser when debugging this, so you can see what pages it clicks, how it navigates. You wont see that with phantom :)

**Comment by SherifWaly** [comment]
@amihaiemil While debugging I realized the following:
At ``LiveWebPageITCase`` the tests fail because ``http://www.amihaiemil.com/2016/05/07/what-is-hateoas.html`` as at page2 of amihaiemil.com so when I try a link at the first page the tests pass but when I try any link at the second page the tests fail. 
Also when I tested for ``http://www.amihaiemil.com/page2/`` I found it in the set of links returned by ``livePage.getLinks()`` 

At ``GraphCrawlITCase`` the first test ``crawlsAllPages`` sometimes pass and others fail throwing `WebDriverException` while the other tests in the class passes so I'm not able to find the error as I ran the tests several times and all of them are passing for this class.

**Comment by amihaiemil** [comment]
@SherifWaly I see, thanks :) can you please open an issue for each of the described problems? (Link to hateoas, wrongly set links on page2 and graphcrawl test)? :)

**Comment by SherifWaly** [comment]
@amihaiemil I have added 2 issues one for the graphcrawl test and the other for hateoas appearing on page2.
